# Generated by Django 4.1.7 on 2023-05-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parcels',
        ),
    ]
