# Generated by Django 4.1.7 on 2023-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(default='bruce-mars.jpg', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='0668629989', max_length=10),
            preserve_default=False,
        ),
    ]
