# Generated by Django 4.1.7 on 2023-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_profile_image_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nakwa',
            field=models.CharField(default='mekkaoui', max_length=10),
            preserve_default=False,
        ),
    ]
