# Generated by Django 4.1.7 on 2023-04-06 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sous_parcel', '0002_sous_parcel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sous_parcel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
