# Generated by Django 4.1.7 on 2023-04-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sous_parcel', '0003_alter_sous_parcel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=500)),
                ('sous_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sous_parcel.sous_parcel')),
            ],
        ),
    ]
