# Generated by Django 4.1.7 on 2023-04-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sous_parcel', '0005_valeur_capter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valeur_capter',
            options={},
        ),
    ]
