# Generated by Django 4.1.7 on 2023-04-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sous_parcel', '0006_alter_valeur_capter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valeur_capter',
            options={'ordering': ('date_added',)},
        ),
    ]
