# Generated by Django 4.1.7 on 2023-04-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        ('sous_parcel', '0012_alter_valeur_capter_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sous_parcel',
            name='user',
        ),
        migrations.AddField(
            model_name='sous_parcel',
            name='parcel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.parcel'),
        ),
    ]
