# Generated by Django 4.1.7 on 2023-05-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sous_parcel', '0018_capteur_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sous_parcel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sous_parcel',
            name='longitude',
        ),
    ]
