# Generated by Django 4.1.7 on 2023-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sous_parcel', '0019_remove_sous_parcel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeur_capter',
            name='température',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valeur_capter',
            name='voltage',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
