# Generated by Django 4.1.7 on 2023-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sous_parcel', '0020_valeur_capter_température_valeur_capter_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='valeur_max',
            field=models.FloatField(default=31),
            preserve_default=False,
        ),
    ]
