# Generated by Django 4.1.7 on 2023-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sous_parcel', '0021_capteur_valeur_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='valeur_min',
            field=models.FloatField(default=19),
            preserve_default=False,
        ),
    ]
